#
# Copyright (C) 2025 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),uke)
KERNEL_PATH ?= device/xiaomi/uke-kernel
include $(call all-makefiles-under,$(LOCAL_PATH))

include $(CLEAR_VARS)

PREBUILT_KERNEL_MODULES_SYSTEM_DLKM := $(TARGET_OUT_SYSTEM_DLKM)/lib/modules
$(PREBUILT_KERNEL_MODULES_SYSTEM_DLKM):
	@mkdir -p $(PREBUILT_KERNEL_MODULES_SYSTEM_DLKM)
	@cp -r $(KERNEL_PATH)/modules/system/6.1.* $(PREBUILT_KERNEL_MODULES_SYSTEM_DLKM)

PREBUILT_KERNEL_MODULES_SYSTEM_DLKM_FLATTEN := $(TARGET_OUT_SYSTEM_DLKM)/flatten/lib/modules
$(PREBUILT_KERNEL_MODULES_SYSTEM_DLKM_FLATTEN):
	@mkdir -p $(PREBUILT_KERNEL_MODULES_SYSTEM_DLKM_FLATTEN)
	@cp -r $(KERNEL_PATH)/modules/system/flatten/* $(PREBUILT_KERNEL_MODULES_SYSTEM_DLKM_FLATTEN)

ALL_DEFAULT_INSTALLED_MODULES += $(PREBUILT_KERNEL_MODULES_SYSTEM_DLKM) $(PREBUILT_KERNEL_MODULES_SYSTEM_DLKM_FLATTEN)

endif
